import type { Metadata } from "next";
import getToken from "./auth/getToken";
import Appbar from "./components/Appbar/Appbar";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import ThemeProvider from "./ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();
  console.log(token);
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="flex bg-Bg text-PrimaryTextColor">
        <ThemeProvider>
          <Navbar token={token} />
          <main className="mx-auto max-w-[80vw] flex-1">
            <Appbar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
